blank_issues_enabled: false
contact_links:
  - name: Soundreactive WLED Discord community
    url: https://discord.gg/4CQRmfR
    about: Please ask and answer questions and discuss setup issues here!
  - name: WLED community forum
    url: https://wled.discourse.group/
    about: For issues and ideas that might need longer discussion.
  - name: WLED kno.wled.ge base
    url:  https://kno.wled.ge/basics/faq/
    about: Take a look at the frequently asked questions and documentation, perhaps your question is already answered!
  - name: SoundReactive WLED Wiki
    url:  https://github.com/atuline/WLED/wiki
    about: Take a look at our well-maintained documentation and guides, maybe your answer is there already !